server:
  port: 0

spring:
  application:
    name: statistics-service

# Swagger Setting
openapi:
  service:
    title: statistics-service doc
    version: v1
    url: http://localhost:8000/${spring.application.name}
springdoc:
  api-docs:
    path: /statistics-service/v3/api-docs
  swagger-ui:
    path: /statistics-service/swagger-ui.html

# log level setting
logging:
  level:
    logging:
      level:
        root: info
        org.hibernate.orm.jdbc.bind: info
        org.hibernate.SQL: info
        springframework.cloud.config: info
        com.buysellgo: info
