server:
  port: 0

spring:
  application:
    name: chat-service

# Swagger Setting
openapi:
  service:
    title: chat-service doc
    version: v1
    url: http://localhost:8000/${spring.application.name}
springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  api-docs:
#    enabled: true
#    path: /v3/api-docs
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - url: /v3/api-docs
#        name: API
#  paths-to-match:
#    - /**
  api-docs:
    path: /chat-service/v3/api-docs
  swagger-ui:
    path: /chat-service/swagger-ui.html

# log level setting
logging:
  level:
    logging:
      level:
        root: info
        org.hibernate.orm.jdbc.bind: info
        org.hibernate.SQL: info
        springframework.cloud.config: info
        com.buysellgo: info