server:
  port: 8031

spring:
  application:
    name: review-service

# Swagger Setting
openapi:
  service:
    title: review-service doc
    version: v1
    url: https://api.buysellgo.shop/${spring.application.name}
springdoc:
  api-docs:
    path: /review-service/v3/api-docs
  swagger-ui:
    path: /review-service/swagger-ui.html

# log level setting
logging:
  level:
    logging:
      level:
        root: info
        org.hibernate.orm.jdbc.bind: info
        org.hibernate.SQL: info
        springframework.cloud.config: info
        com.buysellgo: info